In [1]:
# ==========================================
# NumPy Practice Notebook (Day 6)
# ==========================================

import numpy as np

# ------------------------------------------
# 1. Array Creation (1D, 2D, 3D Arrays)
# ------------------------------------------
# Creating basic NumPy arrays
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:\n", arr_1d)
print("\n2D Array:\n", arr_2d)
print("\n3D Array:\n", arr_3d)

# ------------------------------------------
# 2. Checking Array Dimensions and Data Types
# ------------------------------------------
print("\n--- Array Attributes ---")
print("1D Array Shape:", arr_1d.shape, "| Dimensions:", arr_1d.ndim, "| Data Type:", arr_1d.dtype)
print("2D Array Shape:", arr_2d.shape, "| Dimensions:", arr_2d.ndim, "| Data Type:", arr_2d.dtype)
print("3D Array Shape:", arr_3d.shape, "| Dimensions:", arr_3d.ndim, "| Data Type:", arr_3d.dtype)

# ------------------------------------------
# 3. Generating Arrays using built-in functions
# ------------------------------------------
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((3, 3))
arange_arr = np.arange(0, 10, 2)
linspace_arr = np.linspace(0, 1, 5)

print("\n--- Array Generation ---")
print("np.zeros((2,3)):\n", zeros_arr)
print("\nnp.ones((3,3)):\n", ones_arr)
print("\nnp.arange(0, 10, 2):", arange_arr)
print("np.linspace(0, 1, 5):", linspace_arr)

# ------------------------------------------
# 4. Indexing and Slicing
# ------------------------------------------
grid = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("\n--- Indexing & Slicing ---")
print("Original Grid:\n", grid)
print("Element at row 1, col 2:", grid[1, 2])
print("First two rows:\n", grid[:2, :])
print("Sub-matrix (top-right 2x2):\n", grid[:2, 1:])

# ------------------------------------------
# 5. Reshaping Arrays
# ------------------------------------------
flat_array = np.arange(1, 13)
reshaped_2d = flat_array.reshape((3, 4))
reshaped_3d = flat_array.reshape((2, 2, 3))

print("\n--- Reshaping ---")
print("Original 1D:", flat_array)
print("Reshaped to 3x4 2D:\n", reshaped_2d)
print("Reshaped to 2x2x3 3D:\n", reshaped_3d)

# ------------------------------------------
# 6. Mathematical & Vectorized Operations
# ------------------------------------------
vec_a = np.array([10, 20, 30])
vec_b = np.array([1, 2, 3])

print("\n--- Vectorized Operations ---")
print("Vector Addition:", vec_a + vec_b)
print("Vector Subtraction:", vec_a - vec_b)
print("Vector Multiplication:", vec_a * vec_b)
print("Scalar Power:", vec_b ** 2)

# ------------------------------------------
# 7. Boolean Masking
# ------------------------------------------
data = np.array([12, 45, 7, 23, 89, 3, 56])
mask = data > 20
filtered_data = data[mask]

print("\n--- Boolean Masking ---")
print("Data Array:", data)
print("Mask (data > 20):", mask)
print("Filtered Data:", filtered_data)

# ------------------------------------------
# 8. Broadcasting
# ------------------------------------------
matrix = np.array([[1, 2, 3], [4, 5, 6]])
row_vector = np.array([10, 20, 30])
broadcast_result = matrix + row_vector

print("\n--- Broadcasting ---")
print("Matrix:\n", matrix)
print("Row Vector:", row_vector)
print("Matrix + Row Vector:\n", broadcast_result)

# ------------------------------------------
# 9. Aggregate Functions
# ------------------------------------------
numbers = np.array([[5, 10, 15], [20, 25, 30]])

print("\n--- Aggregate Functions ---")
print("Array:\n", numbers)
print("Mean:", np.mean(numbers))
print("Minimum:", np.min(numbers))
print("Maximum:", np.max(numbers))
print("Median:", np.median(numbers))
print("Column-wise Mean (axis=0):", np.mean(numbers, axis=0))
print("Row-wise Sum (axis=1):", np.sum(numbers, axis=1))

1D Array:
 [1 2 3 4 5 6]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

--- Array Attributes ---
1D Array Shape: (6,) | Dimensions: 1 | Data Type: int64
2D Array Shape: (2, 3) | Dimensions: 2 | Data Type: int64
3D Array Shape: (2, 2, 2) | Dimensions: 3 | Data Type: int64

--- Array Generation ---
np.zeros((2,3)):
 [[0. 0. 0.]
 [0. 0. 0.]]

np.ones((3,3)):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

np.arange(0, 10, 2): [0 2 4 6 8]
np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]

--- Indexing & Slicing ---
Original Grid:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 1, col 2: 60
First two rows:
 [[10 20 30]
 [40 50 60]]
Sub-matrix (top-right 2x2):
 [[20 30]
 [50 60]]

--- Reshaping ---
Original 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to 3x4 2D:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped to 2x2x3 3D:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

--- Vectorized Operations ---
Vector Addition: [11 22 33]
Vector Subtrac